countries = {'afghanistan': {'code': 'AFG', 'eu': False},
 'albania': {'code': 'ALB', 'eu': False},
 'algeria': {'code': 'DZA', 'eu': False},
 'american samoa': {'code': 'ASM', 'eu': False},
 'andorra': {'code': 'AND', 'eu': False},
 'angola': {'code': 'AGO', 'eu': False},
 'anguilla': {'code': 'AIA', 'eu': False},
 'antarctica': {'code': 'ATA', 'eu': False},
 'antigua and barbuda': {'code': 'ATG', 'eu': False},
 'argentina': {'code': 'ARG', 'eu': False},
 'armenia': {'code': 'ARM', 'eu': False},
 'aruba': {'code': 'ABW', 'eu': False},
 'australia': {'code': 'AUS', 'eu': False},
 'austria': {'code': 'AUT', 'eu': True},
 'azerbaijan': {'code': 'AZE', 'eu': False},
 'bahamas': {'code': 'BHS', 'eu': False},
 'bahrain': {'code': 'BHR', 'eu': False},
 'bangladesh': {'code': 'BGD', 'eu': False},
 'barbados': {'code': 'BRB', 'eu': False},
 'belarus': {'code': 'BLR', 'eu': False},
 'belgium': {'code': 'BEL', 'eu': True},
 'belize': {'code': 'BLZ', 'eu': False},
 'benin': {'code': 'BEN', 'eu': False},
 'bermuda': {'code': 'BMU', 'eu': False},
 'bhutan': {'code': 'BTN', 'eu': False},
 'bolivia, plurinational state of': {'code': 'BOL', 'eu': False},
 'bonaire, sint eustatius and saba': {'code': 'BES', 'eu': False},
 'bosnia and herzegovina': {'code': 'BIH', 'eu': False},
 'botswana': {'code': 'BWA', 'eu': False},
 'bouvet island': {'code': 'BVT', 'eu': False},
 'brazil': {'code': 'BRA', 'eu': False},
 'british indian ocean territory': {'code': 'IOT', 'eu': False},
 'brunei darussalam': {'code': 'BRN', 'eu': False},
 'bulgaria': {'code': 'BGR', 'eu': True},
 'burkina faso': {'code': 'BFA', 'eu': False},
 'burundi': {'code': 'BDI', 'eu': False},
 'cambodia': {'code': 'KHM', 'eu': False},
 'cameroon': {'code': 'CMR', 'eu': False},
 'canada': {'code': 'CAN', 'eu': False},
 'cape verde': {'code': 'CPV', 'eu': False},
 'cayman islands': {'code': 'CYM', 'eu': False},
 'central african republic': {'code': 'CAF', 'eu': False},
 'chad': {'code': 'TCD', 'eu': False},
 'chile': {'code': 'CHL', 'eu': False},
 'china': {'code': 'CHN', 'eu': False},
 'christmas island': {'code': 'CXR', 'eu': False},
 'cocos (keeling) islands': {'code': 'CCK', 'eu': False},
 'colombia': {'code': 'COL', 'eu': False},
 'comoros': {'code': 'COM', 'eu': False},
 'congo': {'code': 'COG', 'eu': False},
 'congo, the democratic republic of the': {'code': 'COD', 'eu': False},
 'cook islands': {'code': 'COK', 'eu': False},
 'costa rica': {'code': 'CRI', 'eu': False},
 'croatia': {'code': 'HRV', 'eu': True},
 'cuba': {'code': 'CUB', 'eu': False},
 'curaçao': {'code': 'CUW', 'eu': False},
 'cyprus': {'code': 'CYP', 'eu': True},
 'czech republic': {'code': 'CZE', 'eu': True},
 "côte d'ivoire": {'code': 'CIV', 'eu': False},
 'denmark': {'code': 'DNK', 'eu': True},
 'djibouti': {'code': 'DJI', 'eu': False},
 'dominica': {'code': 'DMA', 'eu': False},
 'dominican republic': {'code': 'DOM', 'eu': False},
 'ecuador': {'code': 'ECU', 'eu': False},
 'egypt': {'code': 'EGY', 'eu': False},
 'el salvador': {'code': 'SLV', 'eu': False},
 'equatorial guinea': {'code': 'GNQ', 'eu': False},
 'eritrea': {'code': 'ERI', 'eu': False},
 'estonia': {'code': 'EST', 'eu': True},
 'ethiopia': {'code': 'ETH', 'eu': False},
 'falkland islands (malvinas)': {'code': 'FLK', 'eu': False},
 'faroe islands': {'code': 'FRO', 'eu': False},
 'fiji': {'code': 'FJI', 'eu': False},
 'finland': {'code': 'FIN', 'eu': True},
 'france': {'code': 'FRA', 'eu': True},
 'french guiana': {'code': 'GUF', 'eu': False},
 'french polynesia': {'code': 'PYF', 'eu': False},
 'french southern territories': {'code': 'ATF', 'eu': False},
 'gabon': {'code': 'GAB', 'eu': False},
 'gambia': {'code': 'GMB', 'eu': False},
 'georgia': {'code': 'GEO', 'eu': False},
 'germany': {'code': 'DEU', 'eu': True},
 'ghana': {'code': 'GHA', 'eu': False},
 'gibraltar': {'code': 'GIB', 'eu': False},
 'greece': {'code': 'GRC', 'eu': True},
 'greenland': {'code': 'GRL', 'eu': False},
 'grenada': {'code': 'GRD', 'eu': False},
 'guadeloupe': {'code': 'GLP', 'eu': False},
 'guam': {'code': 'GUM', 'eu': False},
 'guatemala': {'code': 'GTM', 'eu': False},
 'guernsey': {'code': 'GGY', 'eu': False},
 'guinea': {'code': 'GIN', 'eu': False},
 'guinea-bissau': {'code': 'GNB', 'eu': False},
 'guyana': {'code': 'GUY', 'eu': False},
 'haiti': {'code': 'HTI', 'eu': False},
 'heard island and mcdonald islands': {'code': 'HMD', 'eu': False},
 'holy see (vatican city state)': {'code': 'VAT', 'eu': False},
 'honduras': {'code': 'HND', 'eu': False},
 'hong kong': {'code': 'HKG', 'eu': False},
 'hungary': {'code': 'HUN', 'eu': True},
 'iceland': {'code': 'ISL', 'eu': False},
 'india': {'code': 'IND', 'eu': False},
 'indonesia': {'code': 'IDN', 'eu': False},
 'iran, islamic republic of': {'code': 'IRN', 'eu': False},
 'iraq': {'code': 'IRQ', 'eu': False},
 'ireland': {'code': 'IRL', 'eu': True},
 'isle of man': {'code': 'IMN', 'eu': False},
 'israel': {'code': 'ISR', 'eu': False},
 'italy': {'code': 'ITA', 'eu': True},
 'jamaica': {'code': 'JAM', 'eu': False},
 'japan': {'code': 'JPN', 'eu': False},
 'jersey': {'code': 'JEY', 'eu': False},
 'jordan': {'code': 'JOR', 'eu': False},
 'kazakhstan': {'code': 'KAZ', 'eu': False},
 'kenya': {'code': 'KEN', 'eu': False},
 'kiribati': {'code': 'KIR', 'eu': False},
 "korea, democratic people's republic of": {'code': 'PRK', 'eu': False},
 'korea, republic of': {'code': 'KOR', 'eu': False},
 'kuwait': {'code': 'KWT', 'eu': False},
 'kyrgyzstan': {'code': 'KGZ', 'eu': False},
 "lao people's democratic republic": {'code': 'LAO', 'eu': False},
 'latvia': {'code': 'LVA', 'eu': True},
 'lebanon': {'code': 'LBN', 'eu': False},
 'lesotho': {'code': 'LSO', 'eu': False},
 'liberia': {'code': 'LBR', 'eu': False},
 'libya': {'code': 'LBY', 'eu': False},
 'liechtenstein': {'code': 'LIE', 'eu': False},
 'lithuania': {'code': 'LTU', 'eu': True},
 'luxembourg': {'code': 'LUX', 'eu': True},
 'macao': {'code': 'MAC', 'eu': False},
 'macedonia, the former yugoslav republic of': {'code': 'MKD', 'eu': False},
 'madagascar': {'code': 'MDG', 'eu': False},
 'malawi': {'code': 'MWI', 'eu': False},
 'malaysia': {'code': 'MYS', 'eu': False},
 'maldives': {'code': 'MDV', 'eu': False},
 'mali': {'code': 'MLI', 'eu': False},
 'malta': {'code': 'MLT', 'eu': True},
 'marshall islands': {'code': 'MHL', 'eu': False},
 'martinique': {'code': 'MTQ', 'eu': False},
 'mauritania': {'code': 'MRT', 'eu': False},
 'mauritius': {'code': 'MUS', 'eu': False},
 'mayotte': {'code': 'MYT', 'eu': False},
 'mexico': {'code': 'MEX', 'eu': False},
 'micronesia, federated states of': {'code': 'FSM', 'eu': False},
 'moldova, republic of': {'code': 'MDA', 'eu': False},
 'monaco': {'code': 'MCO', 'eu': False},
 'mongolia': {'code': 'MNG', 'eu': False},
 'montenegro': {'code': 'MNE', 'eu': False},
 'montserrat': {'code': 'MSR', 'eu': False},
 'morocco': {'code': 'MAR', 'eu': False},
 'mozambique': {'code': 'MOZ', 'eu': False},
 'myanmar': {'code': 'MMR', 'eu': False},
 'namibia': {'code': 'NAM', 'eu': False},
 'nauru': {'code': 'NRU', 'eu': False},
 'nepal': {'code': 'NPL', 'eu': False},
 'netherlands': {'code': 'NLD', 'eu': True},
 'new caledonia': {'code': 'NCL', 'eu': False},
 'new zealand': {'code': 'NZL', 'eu': False},
 'nicaragua': {'code': 'NIC', 'eu': False},
 'niger': {'code': 'NER', 'eu': False},
 'nigeria': {'code': 'NGA', 'eu': False},
 'niue': {'code': 'NIU', 'eu': False},
 'norfolk island': {'code': 'NFK', 'eu': False},
 'northern mariana islands': {'code': 'MNP', 'eu': False},
 'norway': {'code': 'NOR', 'eu': False},
 'oman': {'code': 'OMN', 'eu': False},
 'pakistan': {'code': 'PAK', 'eu': False},
 'palau': {'code': 'PLW', 'eu': False},
 'palestinian territory, occupied': {'code': 'PSE', 'eu': False},
 'panama': {'code': 'PAN', 'eu': False},
 'papua new guinea': {'code': 'PNG', 'eu': False},
 'paraguay': {'code': 'PRY', 'eu': False},
 'peru': {'code': 'PER', 'eu': False},
 'philippines': {'code': 'PHL', 'eu': False},
 'pitcairn': {'code': 'PCN', 'eu': False},
 'poland': {'code': 'POL', 'eu': True},
 'portugal': {'code': 'PRT', 'eu': True},
 'puerto rico': {'code': 'PRI', 'eu': False},
 'qatar': {'code': 'QAT', 'eu': False},
 'romania': {'code': 'ROU', 'eu': True},
 'russian federation': {'code': 'RUS', 'eu': False},
 'russia': {'code': 'RUS', 'eu': False},
 'rwanda': {'code': 'RWA', 'eu': False},
 'réunion': {'code': 'REU', 'eu': False},
 'saint barthélemy': {'code': 'BLM', 'eu': False},
 'saint helena, ascension and tristan da cunha': {'code': 'SHN', 'eu': False},
 'saint kitts and nevis': {'code': 'KNA', 'eu': False},
 'saint lucia': {'code': 'LCA', 'eu': False},
 'saint martin (french part)': {'code': 'MAF', 'eu': False},
 'saint pierre and miquelon': {'code': 'SPM', 'eu': False},
 'saint vincent and the grenadines': {'code': 'VCT', 'eu': False},
 'samoa': {'code': 'WSM', 'eu': False},
 'san marino': {'code': 'SMR', 'eu': False},
 'sao tome and principe': {'code': 'STP', 'eu': False},
 'saudi arabia': {'code': 'SAU', 'eu': False},
 'senegal': {'code': 'SEN', 'eu': False},
 'serbia': {'code': 'SRB', 'eu': False},
 'seychelles': {'code': 'SYC', 'eu': False},
 'sierra leone': {'code': 'SLE', 'eu': False},
 'singapore': {'code': 'SGP', 'eu': False},
 'sint maarten (dutch part)': {'code': 'SXM', 'eu': False},
 'slovakia': {'code': 'SVK', 'eu': True},
 'slovenia': {'code': 'SVN', 'eu': True},
 'solomon islands': {'code': 'SLB', 'eu': False},
 'somalia': {'code': 'SOM', 'eu': False},
 'south africa': {'code': 'ZAF', 'eu': False},
 'south georgia and the south sandwich islands': {'code': 'SGS', 'eu': False},
 'south sudan': {'code': 'SSD', 'eu': False},
 'spain': {'code': 'ESP', 'eu': True},
 'sri lanka': {'code': 'LKA', 'eu': False},
 'sudan': {'code': 'SDN', 'eu': False},
 'suriname': {'code': 'SUR', 'eu': False},
 'svalbard and jan mayen': {'code': 'SJM', 'eu': False},
 'swaziland': {'code': 'SWZ', 'eu': False},
 'sweden': {'code': 'SWE', 'eu': True},
 'switzerland': {'code': 'CHE', 'eu': False},
 'syrian arab republic': {'code': 'SYR', 'eu': False},
 'taiwan, province of china': {'code': 'TWN', 'eu': False},
 'tajikistan': {'code': 'TJK', 'eu': False},
 'tanzania, united republic of': {'code': 'TZA', 'eu': False},
 'thailand': {'code': 'THA', 'eu': False},
 'timor-leste': {'code': 'TLS', 'eu': False},
 'togo': {'code': 'TGO', 'eu': False},
 'tokelau': {'code': 'TKL', 'eu': False},
 'tonga': {'code': 'TON', 'eu': False},
 'trinidad and tobago': {'code': 'TTO', 'eu': False},
 'tunisia': {'code': 'TUN', 'eu': False},
 'turkey': {'code': 'TUR', 'eu': False},
 'turkmenistan': {'code': 'TKM', 'eu': False},
 'turks and caicos islands': {'code': 'TCA', 'eu': False},
 'tuvalu': {'code': 'TUV', 'eu': False},
 'uganda': {'code': 'UGA', 'eu': False},
 'ukraine': {'code': 'UKR', 'eu': False},
 'united arab emirates': {'code': 'ARE', 'eu': False},
 'united kingdom': {'code': 'GBR', 'eu': True},
 'great britain': {'code': 'GBR', 'eu': True},
 'united states': {'code': 'USA', 'eu': False},
 'united states of america': {'code': 'USA', 'eu': False},
 'united states minor outlying islands': {'code': 'UMI', 'eu': False},
 'uruguay': {'code': 'URY', 'eu': False},
 'uzbekistan': {'code': 'UZB', 'eu': False},
 'vanuatu': {'code': 'VUT', 'eu': False},
 'venezuela, bolivarian republic of': {'code': 'VEN', 'eu': False},
 'viet nam': {'code': 'VNM', 'eu': False},
 'virgin islands, british': {'code': 'VGB', 'eu': False},
 'virgin islands, u.s.': {'code': 'VIR', 'eu': False},
 'wallis and futuna': {'code': 'WLF', 'eu': False},
 'western sahara': {'code': 'ESH', 'eu': False},
 'yemen': {'code': 'YEM', 'eu': False},
 'zambia': {'code': 'ZMB', 'eu': False},
 'zimbabwe': {'code': 'ZWE', 'eu': False},
 'åland islands': {'code': 'ALA', 'eu': False}}

def fetch_countries():
    return countries